### ISSUE TITLE
[BUG] Items not staying in traphouse stash

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-traphouse#47] opened 2022-11-08 07:49 UTC
**Describe the bug**
Items don't stay in traphouse stash

Error: https://i.imgur.com/reL7lwX.png

**To Reproduce**
1. Enter traphouse
2. Open stash
3. Move in markedbills or any item from config
4. Goes in, but on opening your own inventory it's back there and also the traphouse stash shows as it not in there

**Expected behavior**
Items stay and convert to money based on the config

**Screenshots**
Video: https://youtu.be/dTjZqoSPeXE

**Questions (please complete the following information):**
 - When you last updated: Latest
 - Are you using custom resource? which ones? default qb-core recipie
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by tom-osborne** [comment] 2022-11-08 07:55
I can't see the quantities of items in your video, but are you transferring a stack or a single item?

**Comment by nzkfc** [comment] 2022-11-08 07:56
I tried both, stash is 800 but items combined are only around 150.

I tested this on our dev city and on the fresh qb-server I update daily and it's the same issue.

**Comment by tom-osborne** [comment] 2022-11-09 21:04
@nzkfc I managed to watch your video on a proper screen. 

- Firstly, `markedbills` are a unique item (as they have value associated in their meta data), so you can't stack those. They need to be placed into the traphouse one at a time. Placing 1 `markedbills` item into the traphouse and leaving it for the given process time resulted in the item being consumed and the value available from the traphouse menu for withdrawal. The process time for marked bills by default is 1-5 seconds and can be adjusted here: https://github.com/qbcore-framework/qb-traphouse/blob/main/server/main.lua#L36. I recommend keeping the number of markedbills rewarded from your heists low but adjust their values to suit your economy.
- Secondly, I was able to place 100 steel bars into the traphouse inventory and it took the items fine and began processing. This did however highlight a slightly different issue where the target menu becomes unavailable as the traphouse inventory synchronises every second or so.

So as far as I can see, the traphouse inventory works as intended.

**Comment by nzkfc** [comment] 2022-11-11 08:45
> 

Yeah correct, forgot about 1 at a time, however on a fresh pull, I can see nothing goes into the stash and stays, it instantly returns to inventory? I've checked both items are unique also.

This happens on our dev city, prod city and on my fresh qb-core that I wipe between tests to get the latest.

Vid: https://youtu.be/2E9J17q3aC8

**Comment by jnccloud** [comment] 2022-12-08 01:04
@nzkfc this was introduced when the label was switched in https://github.com/qbcore-framework/qb-traphouse/commit/8d40bb85df6370864645a8fede0329b10a00326f

It's now been fixed with the latest merge in https://github.com/qbcore-framework/qb-traphouse/commit/058ba3fea7b86c2872eadd31eedca59b59fc491b

How do I know? Well, I applied the latest PR (491b) and it created the same problem for me. I went and added that older PR and it fixed it.

**Comment by nzkfc** [comment] 2022-12-15 11:01
> @nzkfc this was introduced when the label was switched in [8d40bb8](https://github.com/qbcore-framework/qb-traphouse/commit/8d40bb85df6370864645a8fede0329b10a00326f)
> 
> It's now been fixed with the latest merge in [058ba3f](https://github.com/qbcore-framework/qb-traphouse/commit/058ba3fea7b86c2872eadd31eedca59b59fc491b)
> 
> How do I know? Well, I applied the latest PR (491b) and it created the same problem for me. I went and added that older PR and it fixed it.

Tried this, items just keep going back into inventory.

I will pull fresh qb build locally again and re-test the resource.

**Closed** 2022-12-18 09:20 UTC
Labels: bug
